<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div id="content" class="col-md-8">
				<ul class="modRuta">
<li><a href="../../index.php" title="Volver al menu">Inicio</a></li>
<li>Política de uso de contenidos Página Web</li>
</ul>
<h1 class="pub">Política de uso de contenidos Página Web</h1>
					<div class="pub">
											<p>
	<strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions.</strong><strong><span class="enlace2"><span style="color: rgb(34, 34, 34); font-family: 'Century Gothic', sans-serif, Verdana; font-size: 15px; line-height: 24.2999992370605px;">&nbsp;</span></span></strong><span style="color: rgb(34, 34, 34); font-family: 'Century Gothic', sans-serif, Verdana; font-size: 15px; line-height: 24.2999992370605px;">El proceso de tecnología de diseño, así como cualquier marca y logotipo que aparezca en esta página son marcas comerciales registradas.</span></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Esta página Web tiene por objeto facilitar al público en general la información relativa a los servicios de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions.</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;Le rogamos leer atentamente la siguiente información antes de hacer uso de esta página Web. La utilización de esta publicación digital y su contenido está sujeta a las condiciones de uso y confidencialidad que más adelante se expondrán. Los siguientes son los términos de un acuerdo legal entre quienes ingresen a esta página&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions.</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;Al acceder, navegar o usar este sitio Web, usted reconoce que ha leído, entendido, y se obliga a cumplir con estos términos y cumplir con todas las leyes y reglamentos aplicables, incluida la exportación y reexportación de leyes y reglamentos de control. Si no acepta dichos términos y condiciones, le rogamos se abstenga de utilizar nuestra página Web y su contenido.</span></p>
<p>
	<strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;podrá, sin previo aviso, en cualquier momento revisar estos Términos de Uso y cualquier otra información contenida en este sitio Web mediante la actualización de este anuncio.&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;también puede realizar mejoras o cambios en los servicios o programas descritos en este sitio en cualquier momento y sin previo aviso.</span></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Este sitio Web incluye avisos sobre servicios y productos propios e información de copyright, cuyos términos deben observarse y seguirse. Ningún contenido de este sitio puede ser copiado, reproducido, recopilado, cargado, publicado, transmitido, distribuido, o utilizado para la creación de servicios derivados de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;sin su consentimiento previo por escrito, salvo que&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;le otorgue su permiso para acceder y visualizar las páginas Web dentro de este sitio, únicamente en su equipo y para su uso personal y no comercial. Esta autorización está condicionada a no modificar el contenido mostrado en este sitio, su mantenimiento intacto, todos los derechos de autor, marcas y otros avisos de propiedad, y su aceptación de cualquiera de los términos, condiciones y avisos que acompañan al contenido o de otro tipo establecidos en este sitio. No obstante lo anterior, cualquier material que esté disponible para su descarga, el acceso, o cualquier otra utilización de este sitio con sus propios términos de licencia, condiciones y avisos, se rige por dichos términos, condiciones y avisos.</span></p>
<p>
	<span style="color: rgb(34, 34, 34); font-size: 1.125em; line-height: 1.6;">Los materiales de esta página Web están protegidos por derechos de autor y cualquier uso no autorizado, así como el incumplimiento de los términos, condiciones o avisos contenidos en ella, pueden violar la normatividad nacional vigente al respecto. La autorización concedida para utilizar esta página se entenderá automáticamente terminada en caso de infringir cualquiera de estas condiciones, estando obligado a destruir inmediatamente cualquier material obtenido o impreso de esta página, sin perjuicio de las acciones judiciales que pueda instaurar&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="color: rgb(34, 34, 34); font-size: 1.125em; line-height: 1.6;">&nbsp;por tal incumplimiento.</span></p>
<p>
	<strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;es titular de todos los derechos sobre el software de la página Web, así como de los derechos de propiedad industrial e intelectual referidos a los contenidos que en ella se incluyan, a excepción de los derechos sobre productos y servicios que no son propiedad de esta Compañía, cuyas marcas están registradas a favor de sus respectivos titulares, y como tal son reconocidas por&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions.</strong></p>
<p>
	<strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;no concede ninguna licencia o autorización de uso de ninguna clase sobre sus derechos de propiedad intelectual, secretos empresariales o sobre cualquier otra propiedad o derecho relacionado con la página Web y sus contenidos.</span></p>
<p>
	<strong style="font-size: 1.125em; line-height: 1.6;">Normas de Confidencialidad y Protección de Datos.</strong></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Se considera norma de confidencialidad y protección de datos toda aquella información personal que el usuario ingresa libre y voluntariamente a la red de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions,</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;así como aquellas que son de obligatorio ingreso, tales como nombre de usuario y palabra clave (password). El usuario podrá ingresar sus datos personales durante su registro al sitio Web. El usuario puede modificar o actualizar parte de esta información en cualquier momento, de esta manera&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;podrá brindarle servicios y contenidos más acordes con su perfil.</span></p>
<p>
	<strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions,</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;se compromete a adoptar una política de confidencialidad y protección de datos, con el objeto de proteger la privacidad de la información personal obtenida a través de su Web Site.</span></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Así mismo, se reserva el derecho de modificar las Normas de Confidencialidad y Protección de Datos que a continuación se detallan a fin de adaptarlas a nuevos requerimientos legislativos, jurisprudenciales, técnicos o todos aquellos que le permitan brindar mejores y más oportunos servicios y contenidos informativos. Por lo cual se aconseja revisar estas normas periódicamente.</span></p>
<p>
	<strong style="font-size: 1.125em; line-height: 1.6;">Protección de la Información Personal.</strong></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">La información proporcionada por el usuario al registrarse en&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions,</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;está resguardada tecnológicamente y sólo podrán acceder a ella, el mismo usuario a través de una palabra clave (password) o en los casos en que el usuario lo requiera, los integrantes del área designada a esta tarea.</span></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">El usuario es el único responsable de mantener su palabra clave (password) y la información de su cuenta. Para disminuir los riesgos&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;recomienda al usuario salir de su cuenta y cerrar la ventana de su navegador cuando finalice su actividad, más aún si comparte su computadora con alguien o utiliza una computadora en un lugar público como una biblioteca o un café Internet.</span></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Si bien&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;posee un sistema de protección tecnológico que va desde sus servidores hasta la salida a Internet, ninguna transmisión por Internet puede garantizar su seguridad al 100%.&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;no puede garantizar que la información ingresada a su sitio web o transmitido utilizando su servicio sea completamente segura, con lo cual el usuario corre su propio riesgo.</span></p>
<p>
	<strong style="font-size: 1.125em; line-height: 1.6;">Confidencialidad de la Información.</strong></p>
<p>
	<strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;no compartirá ni revelará la información confidencial con terceros, excepto que tenga expresa autorización de quienes se suscribieron, o cuando ha sido requerido por orden judicial o legal, o para proteger los derechos de propiedad intelectual u otros derechos de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions.</strong></p>
<p>
	<strong style="font-size: 1.125em; line-height: 1.6;">Aceptación de los términos.</strong></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Esta declaración de Confidencialidad y Protección de Datos está sujeta a los términos y condiciones de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions,</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;con lo cual constituye un acuerdo legal entre el usuario e&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions</strong><strong style="color: rgb(23, 162, 190); font-size: 15px; line-height: 24.2999992370605px;">.</strong></p>
<p>
	<span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">Si el usuario utiliza los servicios de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions,</strong><span style="font-size: 1.125em; line-height: 1.6; color: rgb(34, 34, 34);">&nbsp;significa que ha leído, entendido y aceptado los términos antes expuestos. Si no está de acuerdo con ellos tiene la opción de no proporcionar ninguna información personal, o no utilizar el servicio de&nbsp;</span><strong style="line-height: 23.466667175293px; color: rgb(23, 162, 190); font-size: 15px;">Energy Equipment Solutions.</strong></p>
					</div>

		
			</div>
</body>
</html>